### ISSUE TITLE
Is the weight file  compact with original repo?

### ISSUE THREAD

**Issue by vehxianfish** [stesha2016/lanenet-enet-hnet#1]
I use  original repo weight files and code `python lanenet_hnet_predict.py --image_path ./data/tusimple_data/training/gt_image/0001.png --lanenet_weights ./model/tusimple_lanenet/tusimple_lanenet_vgg.ckpt ./model/hnet/hnet-2000` to predict single picture
but some fault happens.  
`  <no registered kernels>

         [[Node: lanenet_model/inference/LaneNetBase/bottleneck1_0_main_max_pool =MaxPoolWithArgmax[T=DT_FLOAT, Targmax=DT_INT64, ksize=[1, 2, 2, 1], padding="SAME", strides=[1, 2, 2, 1]](lanenet_model/inference/LaneNetBase/iniatial_block_concat)]]
`
it seems weights file is not match.If possible,can you share weight file for me.thank you！

**Comment by stesha2016** [comment]
I have modified the backbone to ENet, so the original weights file will not match. 
Lanenet-ENet weights:
链接: https://pan.baidu.com/s/10rYFXoNDMW1RjNa3rvD9OA 提取码: qdt4 
H-Net weights:
链接: https://pan.baidu.com/s/1n1ZMipCy-xDgum988H6q0w 提取码: ff2g

**Comment by vehxianfish** [comment]
thank u very much,that's cool!appreciation for your work!

**Comment by lzb863** [comment]
Thank you for your great work.
when I run python lanenet_hnet_predict.py  --image_path ./data/training_data_example/image/0001.png  --lanenet_weights ./model/tusimple_lanenet_enet/tusimple_lanenet_enet_2019-05-08-11-11-01.ckpt-100000  --hnet_weights ./model/hnet/hnet-2000, the same fault as vehxianfish happened.

[[Node: lanenet_model/inference/LaneNetBase/bottleneck1_0_main_max_pool = MaxPoolWithArgmax[T=DT_FLOAT, Targmax=DT_INT64, ksize=[1, 2, 2, 1], padding="SAME", strides=[1, 2, 2, 1]](lanenet_model/inference/LaneNetBase/iniatial_block_concat)]]



> I have modified the backbone to ENet, so the original weights file will not match.
> Lanenet-ENet weights:
> 链接: https://pan.baidu.com/s/10rYFXoNDMW1RjNa3rvD9OA 提取码: qdt4
> H-Net weights:
> 链接: https://pan.baidu.com/s/1n1ZMipCy-xDgum988H6q0w 提取码: ff2g

the models I used from the lines . Is there some thing wrong with the models?

**Comment by stesha2016** [comment]
fixed
